title: Austin Murphy
email: ausmurp@gmail.com
url:   "http://ausmurp.com"
description: >
  Personal portfolio and blog site.

# Build settings
markdown: kramdown
paginate:1

# Sass settings
sass:
  sass_dir: assets/stylesheets
  style: :compressed

gems:
  jekyll-sitemap
  jekyll-paginate
